#!/bin/bash

RANDOM=$(date '+%s')

if [ ! -e '~/.wordlist' ]; then
	aspell dump master | tr -d '[:punct:]' | sort | uniq > ~/.wordlist
fi

# The arg should be the number of words needed
shuf -n "$1" ~/.wordlist | sed ':a;N;$!ba;s/\n/-/g'
